### ISSUE TITLE
Web Store Links

### ISSUE THREAD

**Issue by vhscom** [sveltejs/svelte-devtools#104]
The Chrome Web Store link I followed from the README was last updated in early 2021 by previous maintainer. Is there a new web store link or should we build/install from source? If we should install from source, could we have the README updated so it's no longer linking to an outdated Chrome extension?

**Comment by bershanskiy** [comment]
> The Chrome Web Store link I followed from the README was last updated in early 2021 by previous maintainer.

This extension has not been updated in a while (since June 2021), but the published version is even more out of date.

> Is there a new web store link or should we build/install from source?

If you would like to use it, I would recommend building from source.

> If we should install from source, could we have the README updated so it's no longer linking to an outdated Chrome extension?

There are plans to release to CWS eventually,<sup>TM</sup> but no specific deadlines were announced (read "this will never happen").
