### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by D3strukt0r** [sveltejs/svelte-devtools#124]
I can't find the application anymore on the Chrome web store

https://chrome.google.com/webstore/detail/ckolcbmkjpjmangdbmnkpjigpkddpogn

Was it automatically taken down, what's going to happen to this tool?

**Comment by sanba-anass** [comment]
use vue

**Comment by D3strukt0r** [comment]
@sanba-anass you mean to use [Vue.js devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd)? It actually understands Svelte Code??

**Comment by parker-nilson** [comment]
@D3strukt0r I am not sure what happened either... The extension still exists for Firefox, though! If you want you can still build the extension from source (simple instructions in readme [here](https://github.com/sveltejs/svelte-devtools#chrome)). That's what I am going to do!

**Comment by D3strukt0r** [comment]
@parker-nilson hmm, I recently switched to Brave because Firefox got too annoying as a Dev and User. Also built extensions don't synchronize between browsers. I have started to work on a Fork and update all tools (and maybe manifest v3), but it might still take some time until I consider it ready and push to the web store.

**Comment by bershanskiy** [comment]
Related to issue #104.

**Comment by bershanskiy** [comment]
@D3strukt0r

> I have started to work on a Fork

Would you be interested in publishing that on GitHub under MIT license as well?

> and update all tools (and maybe manifest v3), but it might still take some time until I consider it ready and push to the web store.

I'm not sure what you mean by "maybe manifest v3", since it is a requirement for all new extensions on CWS since a while back. Unless you have a stash or pre-registered extension ids created prior to MV3 requirement.

Back in 2021, I made a few PRs which addressed the most pressing issues and improved manifest v3 compatibility. Unfortunately, by then the original author (red hatter) had lost interest in this extension and merging process stretched to the point when I moved on as well.

I expected that after red hatter transferred the repo to main Svelte organization, the development would pick up pace allowing be to submit more PRs, but that did not happen yet. Since the main extension CWS listing is offline, I I have a few things in mind (a sprint timeline) and if you are interested we could discuss possibility of a collaboration on this.

**Comment by bershanskiy** [comment]
Answer to the original question:

The last official release of Svelte Dev Tools was [1.3.0](https://github.com/sveltejs/svelte-devtools/releases/tag/1.3.0) in January 2021. CWS page is currently offline, but there are multiple sites online which host old official release files. I found this one:
https://www.crx4chrome.com/
hosting Svelte Dev Tools here:
https://www.crx4chrome.com/extensions/ckolcbmkjpjmangdbmnkpjigpkddpogn/

I downloaded the 1.3.0, but did not actually validate it yet (test that it installs, test that it has not been tampered with). I plan to do that as part of restarting the project and preparing for CWS release. I'll try to publish an update here once that happens.

**Comment by D3strukt0r** [comment]
@bershanskiy 

> Would you be interested in publishing that on GitHub under MIT license as well?

Yes sure :)

> I'm not sure what you mean by "maybe manifest v3"

Ah didn't know that. I'm pretty new to Chrome extensions. I guess then I just have to.

I'm also currently trying to learn how everything works with an [Emoji extension](https://github.com/D3strukt0r/emoji-helper) that has also been abandoned. I'm trying to build everything with [Vite.js](https://vitejs.dev/) and [CRXJS](https://crxjs.dev/vite-plugin) now, but The Svelte Devtools are a bit more complicate, that's why I meant I might still need a moment.

On my Github profile you have my contact email, you can send me your discord/telegram there. then we can discuss :)
I would probably also give you full access to the repo, to make everyone's life easier

Oh an here the repo https://github.com/D3strukt0r/svelte-devtools

**Comment by bershanskiy** [comment]
I filed #126 with a moderately detailed explanation of changes required for future publication to CWS.
