### ISSUE TITLE
This isn't on Chrome's Extension webstore

### ISSUE THREAD

**Issue by corysimmons** [sveltejs/svelte-devtools#158]
The URL on the Chrome badge 404s https://chrome.google.com/webstore/detail/svelte-devtools/ckolcbmkjpjmangdbmnkpjigpkddpogn

**Comment by dominikg** [comment]
it's not released yet

**Comment by ignatiusmb** [comment]
The link is from a previous version that has been taken down from the Chrome web store, there have been a couple of issues asking this as well and they were closed in #133 with the reason in the description, but the submission process is taking longer than we hoped to be. We'd also like to make sure it's polished enough for the release since it won't be easy to update an extension once it's published to the store.

It should hopefully be released sometime around this month, we'll update the URL once it's published.
