### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/svelte-devtools#63]
Is this abandoned?

**Comment by nickpoulos** [comment]
Pretty much, I haven't been able to get it working in months, and yet there is no other alternative yet.

**Comment by grandslammer** [comment]
It's a real shame if this has been abondoned.

I wish Svelte had an official devtools extension like [VueJS](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd)! There's also a ([beta](https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg)) version for Vue 3

Might be worth while requesting an extension from the official team?

**Comment by dennisjlee** [comment]
@nickpoulos I have been using this extension successfully for several months - what's been broken for you?

**Comment by skamansam** [comment]
@dennisjlee What version of svelte are you using? Here are my deps and it just tells me to reload my page, even after I reload my page.
```
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "next",
		"@typescript-eslint/eslint-plugin": "^5.10.1",
		"@typescript-eslint/parser": "^5.10.1",
		"eslint": "^7.32.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^3.2.1",
		"prettier": "^2.4.1",
		"prettier-plugin-svelte": "^2.4.0",
		"svelte": "^3.44.0",
		"svelte-check": "^2.2.6",
		"svelte-preprocess": "^4.10.1",
		"tslib": "^2.3.1",
		"typescript": "^4.4.3",
		"postcss": "^8.4.5",
		"postcss-load-config": "^3.1.1",
		"autoprefixer": "^10.4.2",
		"tailwindcss": "^3.0.12"
```

**Comment by ghoshsanjoy78** [comment]
Tried everything. Simply does not work for me :-(

```
  "devDependencies": {
    "@sveltejs/adapter-auto": "next",
    "@sveltejs/kit": "next",
    "autoprefixer": "^10.4.4",
    "postcss": "^8.4.12",
    "svelte": "^3.44.0",
    "tailwindcss": "^3.0.23"
  },
```

Chrome version: 100.0.4896.75
Windows 11

**Comment by dennisjlee** [comment]
I also have been unable to get the extension to work lately, even though it used to work on the same Chrome installation.

**Comment by wheezard** [comment]
This extension doesn't work for me in all chromium browsers (didn't test in firefox), but the error happens here, in the background page:
![Error](https://user-images.githubusercontent.com/90904039/174099374-668f1274-44dd-4ae7-b653-5cd770436a9e.png)
This is why it doesn't work - it thinks that the connection is a tab, because of the double-slash here:
![double slash](https://user-images.githubusercontent.com/90904039/174099616-64fd2574-5f2c-4198-8b27-489fee2d02a7.png)
While the `.getURL()` function returns a single slash.
![oneslash](https://user-images.githubusercontent.com/90904039/174099713-0a4b89e4-fdc8-4c75-8208-007aaf5ef4e9.png)

I was able to fix it with one change to the 6th line in `dest/devtools/index.js`:
```diff
chrome.devtools.panels.create(
  'Svelte',
  chrome.devtools.panels.themeName == 'dark'
    ? '/devtools/svelte-logo-dark.svg'
    : '/devtools/svelte-logo-light.svg',
-  '/devtools/panel.html',
+ 'devtools/panel.html',
  panel =>
    panel.onShown.addListener(() =>
      chrome.devtools.inspectedWindow.eval(
        'if (window.__svelte_devtools_select_element) window.__svelte_devtools_select_element($0)',
        (result, err) => err && console.error(err)
      )
    )
)
```

**Comment by iandoesallthethings** [comment]
Fantastic! Are you planning on making a pull request? I'd love to not have to switch to firefox for my sveltekit projects.

**Comment by KimhoutSam** [comment]
same 3.50.1

**Comment by nextmat** [comment]
@benmccann provided some more context [here](https://github.com/sveltejs/svelte-devtools/pull/81#issuecomment-1245920809), it sounds like the Svelte team is managing this repo but not be able to release new versions yet. 

As of today installing the plugin still installs 1.3.0, released Jan 2021.

I'm exploring Svelte and surprised to see this broken since it feels like an important part of the ecosystem. Do folks find they just don't need this given their workflows or are you building this manually if you want to use it with improvements?

Any further updates?

**Comment by FeldrinH** [comment]
Personally I lean more on the 'just don't need this' side but I would still be very happy to see this prpject maintained.

**Comment by groundbirdaircat** [comment]
I would absolutely use this. Glad to hear the official team has this in the works

**Comment by FractalHQ** [comment]
@nextmat I've found I don't need it, but sometimes I use a modified version of [svelte-toy](https://github.com/leveluptuts/svelte-toy) which is a nifty tool.  Looking forward to this being revived though! 🙏

**Comment by joshwcorbett** [comment]
Extension hardly works with the new svelte 4 release

**Comment by benmccann** [comment]
If anyone would like to send a PR for Svelte 4, we'd be happy to review.

Unfortunately we don't have access to publish to the existing webstore accounts, so will have to create a new one to publish new versions of the extensions and users will have to uninstall the old extension and install the new one instead.
